# Generated by Django 4.0.8 on 2022-12-07 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_milestone_delete_projectsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='hierarchycal_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.project'),
        ),
    ]
