# Generated by Django 4.0.8 on 2022-12-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_milestone_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='hierarchycal_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='milestone',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
