# Generated by Django 4.0.8 on 2022-12-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_milestone_hierarchycal_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(),
        ),
    ]
