# Generated by Django 4.0.8 on 2022-12-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_milestone_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
