# Generated by Django 4.0.8 on 2022-12-10 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tag_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='project',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='test',
        ),
        migrations.AddField(
            model_name='project',
            name='milestones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='core.milestone'),
            preserve_default=False,
        ),
    ]
