# Generated by Django 4.0.8 on 2022-12-10 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_milestone_project_remove_tag_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='milestones',
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.project'),
            preserve_default=False,
        ),
    ]
