# Generated by Django 4.0.8 on 2022-12-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_project_milestones_milestone_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='parent',
        ),
    ]
