# Generated by Django 4.0.8 on 2022-12-12 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_milestone_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.project'),
        ),
    ]
